### ISSUE TITLE
[Documentation] Update code of conduct

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/Passliss#177]
### What is the problem?

Update the email address in the code of conduct. (leopeyronnet.corp@hotmail.com)

**Comment by Pathholder1806** [comment]
Hey is this issue still open ? Would like to correct it

**Comment by Leo-Peyronnet** [comment]
Yes, if you want :)

**Comment by Pathholder1806** [comment]
I have done the change. Shall I make a pull request now ?

**Comment by Leo-Peyronnet** [comment]
Yes!
